# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-browsers
      - image: geranium/custamdvwa    
        name: example123123123.com

    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout    
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run: echo -e "Host pfd.vaddy.net\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      #ここから下がVaddyのセットアップ
      - run: sudo rm -rf /var/lib/apt/lists/* && sudo apt-get update
      - run: sudo apt-get install openjdk-8-jre
      - run: git clone https://github.com/vaddy/go-vaddy.git
    
      - run: touch go-vaddy/privatenet/conf/vaddy.conf
      - run: echo export VADDY_AUTH_KEY=\"$VADDY_AUTH_KEY\" >>  go-vaddy/privatenet/conf/vaddy.conf  
      - run: echo export VADDY_FQDN=\"$VADDY_FQDN\" >>  go-vaddy/privatenet/conf/vaddy.conf
      - run: echo export VADDY_VERIFICATION_CODE=\"$VADDY_VERIFICATION_CODE\" >>  go-vaddy/privatenet/conf/vaddy.conf
      - run: echo export VADDY_USER=\"$VADDY_USER\" >>  go-vaddy/privatenet/conf/vaddy.conf
      - run: echo export VADDY_YOUR_LOCAL_IP=\"`hostname -i|sed -e 's/.3$//g'`.4\" >> go-vaddy/privatenet/conf/vaddy.conf
      - run: echo export export VADDY_YOUR_LOCAL_PORT=\"$VADDY_YOUR_LOCAL_PORT\" >> go-vaddy/privatenet/conf/vaddy.conf
      - run: cat go-vaddy/privatenet/conf/vaddy.conf
      - run: cd go-vaddy/privatenet/ && ./vaddy_privatenet.sh connect
      - run: cd go-vaddy/privatenet/ && ./vaddy_privatenet.sh scan

workflows:
  version: 2
  normal_workflow:
    jobs:
      - build:
          context: VADDY

#  繰り返し用
#  schedule_workflow:
#    triggers:
#      - schedule:
#          cron: "1 7 * * *" # UTCで記述。-9
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - build
